### PR TITLE
Add '.one' method

### PR DESCRIPTION
**Pull request by dykov**
-----
[View rendered readme.md](https://github.com/dykov/enumerable4j/blob/add-one-method/readme.md)

### CODE REVIEW

**Review by dgroup — CHANGES_REQUESTED** [review]
Its better to use method ‘this.count(first, others) == 1’

**Comment by dykov** [comment]
> Its better to use method ‘this.count(first, others) == 1’

should it have the `one(Predicate<X> first, Predicate<X> ...other)` structure?

**Comment by dgroup** [comment]
@dykov yes

**Review by dgroup — APPROVED** [review]

**Comment by dgroup** [comment]
@rultor merge

**Pull request merged**
